version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cabreratoxy/pyopera
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Lint/Formatting/Testing/Coverage
          command: |
            black . --check
            isort --check --diff .
            pylint $(find . -name "*.py" | xargs)
            coverage run --source pyopera -m pytest
            coverage report --skip-empty --fail-under=85
      # - run:
      #     name: Deploy to Test Pypi
      #     command: 

  # deploy-to-testpy:
  #   docker:
  #     - image: cabreratoxy/pyopera:0.0.1
  #   steps:
  #     - checkout


workflows:
  test-package:
    jobs:
      - build-and-test
