version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cabreratoxy/pyopera:0.0.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Lint/Formatting/Testing/Coverage
          command: |
            black . --check --exclude="docs/"
            isort --check --diff . --skip docs/
            pylint $(find . -name "*.py" | xargs) --ignore-paths docs/
            coverage run --source pyopera -m pytest
            coverage report --skip-empty --fail-under=85
      # - run:
      #     name: Deploy to Test Pypi
      #     command: 

  deploy-to-testpy:
    docker:
      - image: cabreratoxy/pyopera:0.0.2
    steps:
      - checkout
      - run:
          name: Deploy to Test Pypi
          # Add autoversioning here
          command: |
            poetry config repositories.testpypi https://test.pypi.org/legacy/
            poetry publish --repository testpypi --build -u ${PYPI_USERNAME} -p ${TEST_PYPI}
  
    deploy-to-pypi:
    docker:
      - image: cabreratoxy/pyopera:0.0.2
    type: approval
    steps:
      - checkout
      - run:
          name: Deploy to Pypi
          # Add autoversioning here
          command: |
            poetry config repositories.pypi https://upload.pypi.org/legacy/
            poetry publish --repository pypi --build -u ${PYPI_USERNAME} -p ${PYPI}


workflows:
  test-package:
    jobs:
      - build-and-test
      - deploy-to-testpy:
          filters:
            branches:
              only: main
      - deploy-to-pypi
