ENDPOINTS = [
    "BCF",
    "LogBCF",
    "BP",
    "LogP",
    "MP",
    "VP",
    "LogVP",
    "WS",
    "AOH",
    "BioDeg",
    "RB",
    "ReadyBiodeg",
    "HL",
    "LogHL",
    "KM",
    "LogKM",
    "KOA",
    "Koc",
    "LogKoc",
    "RT",
    "pKa",
    "LogD",
    "CERAPP",
    "ER",
    "CoMPARA",
    "AR",
    "CATMoS",
    "AcuteTox",
]
ALL_ENDPOINTS_PARAMETIZED = [([endpoint]) for endpoint in ENDPOINTS]
SAMPLE_OF_ENDPOINTS_TOGETHER = [
    ENDPOINTS[0],
    ENDPOINTS[5],
    ENDPOINTS[8],
    ENDPOINTS[10],
    ENDPOINTS[14],
]
